### PR TITLE
 add WorldMania_simpleCN.lang file 

### PR DESCRIPTION
**Pull request by Moius**
add ZH-CN translate

### CODE REVIEW

**Comment by dado997** [comment]
The plugin cannot read any cyrillic character or symbol, so if i add the ZH-CN translate, the plugin will write only things like ?????

**Comment by Moius** [comment]
> 该插件无法读取任何西里尔字母或符号，因此，如果我添加ZH-CN转换，该插件将仅写入?????

hmmm but i can use it
maybe i should check my document？

**Comment by Moius** [comment]
Hello, author. I still don't quite understand what the Cyrillic letters and symbols you mentioned contains, but the zh-CN file should not contain the letters and symbols you mentioned earlier. I tried it again. It works on my server, which is very strange.

**Comment by dado997** [comment]
> Hello, author. I still don't quite understand what the Cyrillic letters and symbols you mentioned contains, but the zh-CN file should not contain the letters and symbols you mentioned earlier. I tried it again. It works on my server, which is very strange.

Oh, i don't know why but for me, it only says ??????? at every word that sends to the console or at the players, this can be maybe caused because my windows version is in Italian, so it can't read the chinese characters. If to you works, i will add it to the default Languages folder. Because if works for you, its only a my problem.

Excuse me for my bad english but i'm italian.

**Comment by Moius** [comment]
Thank you very much, by the way, I can repost your plug-in to the forum in China: mcbbs-- https://www.mcbbs.net/  ? It is the largest mc forum in China. I will indicate to you that you are the author of this plugin and provide a link to the spigot homepage.

**Comment by dado997** [comment]
Ok, but make sure to write that its a my plugin, and link the spigot page.

**Pull request closed without merging**
